### PR TITLE
[CHG] - add compatibility for visual studio for mac

### PR DESCRIPTION
**Pull request by marra85**
Visual Studio for Mac expects a <PropertyGroup> node in the csproj file, without it the IDE throws an NRE.

This PR adds a workaround so the solution can be loaded.

I've also added to the .gitignore the tools/ folder and build.ps1 file which are created by the bootbuild.ps1 script.

### CODE REVIEW

**Comment by jsmarcus** [comment]
The TargetFrameworks are defined in the Directory.Build.props. Does VS4Mac not support that structure yet?

**Comment by marra85** [comment]
Nope. When you load the solution the IDE throws an error like this.

error

**Comment by marra85** [comment]
It could be related to this [issue](https://developercommunity.visualstudio.com/content/problem/89735/vs-for-mac-fails-to-load-an-sdk-csproj-without-pro.html)

maybe just adding an empty <propertygroup> node resolves this issue.

**Comment by marra85** [comment]
adding an empty propertygroup node works.

`<PropertyGroup><!-- VS4Mac workaround --></PropertyGroup>`

the comment is there to prevent the node being removed by VS.

If you are okay with the description, I'll update the PR.

**Comment by jsmarcus** [comment]
The current description works for me.

**Pull request merged**
